compilers::
  - compiler:
      spec: gcc@10
      paths:
        cc: /usr/bin/gcc-10
        cxx: /usr/bin/g++-10
        f77: /usr/bin/gfortran-10
        fc: /usr/bin/gfortran-10
      flags: {}
      operating_system: sles12
      target: x86_64
      modules:
      - gnu/10
      environment: {}
      extra_rpaths: []
